# Generated by Django 5.2.17 on 2026-08-11 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Closed', 'Closed')], default='Draft', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('goal_type', models.CharField(choices=[('KPI', 'KPI'), ('OKR', 'OKR'), ('Project Goal', 'Project Goal'), ('Learning Goal', 'Learning Goal')], max_length=50)),
                ('weightage', models.DecimalField(decimal_places=2, help_text='Weightage in percentage', max_digits=5)),
                ('target_value', models.CharField(blank=True, max_length=255, null=True)),
                ('achieved_value', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Not Started', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='employees.employee')),
                ('performance_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='performance.performancecycle')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('manager_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('final_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('self_comments', models.TextField(blank=True, null=True)),
                ('manager_comments', models.TextField(blank=True, null=True)),
                ('hr_comments', models.TextField(blank=True, null=True)),
                ('promotion_recommended', models.BooleanField(default=False)),
                ('increment_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Self Submitted', 'Self Submitted'), ('Manager Reviewed', 'Manager Reviewed'), ('HR Approved', 'HR Approved'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='employees.employee')),
                ('performance_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='performance.performancecycle')),
            ],
        ),
    ]
